### ISSUE TITLE
Feedback Volledigheid (van Mediahuis)

### ISSUE THREAD

**Issue by julia-stevens** [RickFDND/look-and-feel-styleguide#10]
## Feedback Volledigheid (van Mediahuis)

Jullie zijn vrij volledig, we zien alleen in CSS dat er met comments nog ruimte is gemaakt voor formulieren, gaan jullie dit nog toevoegen? 

@vsheo
@poormoa00

**Comment by saschavanvliet** [comment]
Hoi wij hebben helaas nog geen formulieren in onze opdracht dus wij gaan dit nog niet toevoegen.

**Comment by saschavanvliet** [comment]
@Nayomekaia Dit is dit nog niet geïmplementeerd. Jij hebt dit gemaakt, dus zou jij dit nog kunnen toevoegen?

**Comment by Nayomekaia** [comment]
@saschavanvliet ja ik heb inlog/registreren formulier toegevoegd  ( commit 018e774)

**Comment by saschavanvliet** [comment]
Goed gedaan! Ik heb echter wel een vraag: Waarom heb je hier het font size aangepast?     

<img width="833" alt="image" src="https://github.com/user-attachments/assets/56bab4fa-5ce6-473a-947f-729e772ee91c">
@Nayomekaia

**Comment by Nayomekaia** [comment]
@saschavanvliet ik heb formaat aangepast doordat ik deze voor de header s iets te groot vond en deze heer erg leek op de size van de header m
