### ISSUE TITLE
Feedback Custom properties & Herhaling (van Mediahuis)

### ISSUE THREAD

**Issue by julia-stevens** [RickFDND/look-and-feel-styleguide#11]
## Feedback Custom properties & Herhaling (van Mediahuis)

De custom properties staan in de `body`. Dit doen jullie goed. 

https://github.com/RickFDND/look-and-feel-styleguide/blob/129065882527dd9013ef6567bf38c5e1ad0bd85d/Drop%26Heal.css#L104-L129
De styling van de `a` en `button` zijn exact hetzelfde. Misschien kunnen dit samenvoegen tot één. Je zou hier bijvoorbeeld een `class` bij kunnen definiëren in HTML en in CSS hoef je dan dus maar één keer de styling te schrijven.

https://github.com/RickFDND/look-and-feel-styleguide/blob/129065882527dd9013ef6567bf38c5e1ad0bd85d/Drop%26Heal.css#L127
Hier schrijven jullie de `font-size: 16px`, maar hier hebben jullie in de body een custom property voor gedefinieerd. Misschien kan je dit nog aanpassen? 

@vsheo
@poormoa00

**Comment by Nayomekaia** [comment]
@RickFDND  en ik hebben deze issue samen afgesloten, ik heb de code samengevoegd zodat onnodige code voorkomen word en rick heeft de font-size issue opgelost ( dit stond er in als 2 aparte issues vandaar de uitleg)
