### ISSUE TITLE
Onduidelijke naamgeving buttons

### ISSUE THREAD

**Issue by irisvw** [RickFDND/look-and-feel-styleguide#2]
Deze buttons hebben een onduidelijke rol:
    --btn-rouwtaak1: #64AAC7;
    --btn-rouwtaak2: #984A4A;
    --btn-rouwtaak3: #6E9158;
    --btn-rouwtaak4: #7C6097;

In tegenstelling tot bijvoorbeeld "secondary-color", waar het meteen duidelijk is waar het over gaat, zou ik geen idee hebben wat "btn-rouwtaak3" is en wanneer ik die zou gebruiken.

Review door @reyrey-https @yamenAl @SuleymanHG @irisvw @DeBosOs

**Comment by Nayomekaia** [comment]
ik heb de feedback verwerkt, in de code heb ik --btn-rouwtaak1 veranderd in --btn-color-routaak1 waardoor het duidelijker word dat dit gaat over de kleuren van de rouwtaken.
