### ISSUE TITLE
Kleuren code primary color niet goed getypt

### ISSUE THREAD

**Issue by SuleymanHG** [RickFDND/look-and-feel-styleguide#3]
https://github.com/RickFDND/look-and-feel-styleguide/blob/main/Drop%26Heal.css#L7

De kleur code van de primary op regel 7 is niet helemaal goed. Het hoort #FFFFFF te zijn in plaats van #FFFF.

**Issue gemaakt door: @SuleymanHG, @irisvw, @reyrey-https, @YemenAl**

**Comment by saschavanvliet** [comment]
Hoi bedankt voor jullie feedback. Ik heb dit gelijk aangepast!
