### ISSUE TITLE
Herhaling van code

### ISSUE THREAD

**Issue by irisvw** [RickFDND/look-and-feel-styleguide#6]
De properties van `<a>` en `<button>` zijn identiek. https://github.com/RickFDND/look-and-feel-styleguide/blob/main/Drop%26Heal.css#L103-L135

Je kunt dit dan verkorten door dit te schrijven als 

```
a, button {
    text-decoration: none;
    background-color: var(--background-color);
    color: var(--primary-color);
    border-radius: 30.5px;
    border: 1px solid var(--primary-color); 
    padding: 15px 20px;
    font-size: 16px;
    cursor: pointer;

    &:hover {
        background-color: var(--primary-color);
        color: var(--background-color);
    }
}
```

Review door @reyrey-https @yamenAl @SuleymanHG @irisvw @DeBosOs

**Comment by Nayomekaia** [comment]
issue verwerkt in code
