### ISSUE TITLE
Feedback Indeling Stylesheet (van Mediahuis)

### ISSUE THREAD

**Issue by julia-stevens** [RickFDND/look-and-feel-styleguide#8]
## Feedback Indeling Stylesheet

De indeling is logisch, met comments geven jullie aan waar de code om gaat. 

Alleen de indeling van de `figure` begrijpen we niet helemaal. Is het nodig om dit te nesten? Kunnen dit niet gewoon losse classes zijn? 
https://github.com/RickFDND/look-and-feel-styleguide/blob/129065882527dd9013ef6567bf38c5e1ad0bd85d/Drop%26Heal.css#L31-L56

@vsheo
@poormoa00

**Comment by FinnnBak** [comment]
Heb van de figure nu losse classes gemaakt
