### ISSUE TITLE
Feedback Naamgeving & Begrijpelijkheid (van Mediahuis)

### ISSUE THREAD

**Issue by julia-stevens** [RickFDND/look-and-feel-styleguide#9]
## Feedback Naamgeving & Begrijpelijkheid (van Mediahuis)

Over het algemeen is de naamgeving duidelijk en consistent. 

De kleuren geven jullie allemaal aan met 'rouwtaak', misschien kunnen jullie hier een meer beschrijvende naam aan geven, denk bijvoorbeeld aan: primary, secondary, etc. 

@vsheo
@poormoa00

**Comment by Nayomekaia** [comment]
feedback verwerkt, door de benaming meer te specialiseren ( dubbele issue)
